# Generated by Django 2.2.10 on 2020-05-07 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=1)),
                ('spacialist', models.CharField(default='', max_length=150)),
                ('currentwork', models.CharField(default='', max_length=150)),
                ('company', models.CharField(default='', max_length=150)),
                ('Country', models.CharField(default='', max_length=150)),
                ('state', models.CharField(default='', max_length=1)),
                ('type', models.CharField(default='Normal Member', max_length=150)),
                ('short_description', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppData',
            fields=[
                ('ROW_ID', models.AutoField(primary_key=True, serialize=False)),
                ('KEY', models.CharField(max_length=50, unique=True)),
                ('VALUE', models.TextField()),
                ('CREATED', models.DateTimeField(auto_now_add=True)),
                ('UPDATED', models.DateTimeField(auto_now=True)),
                ('CREATEDBY', models.CharField(max_length=50)),
                ('UPDATEDBY', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='')),
                ('img', models.ImageField(upload_to='')),
                ('type', models.CharField(default='User', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_Files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
