# Generated by Django 2.2.10 on 2020-05-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
     
    ]
