# Generated by Django 2.2.10 on 2020-05-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20200507_2304'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='projects',
            name='release_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
