# Generated by Django 2.2.10 on 2020-05-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20200507_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='released_date',
        ),
        migrations.AlterField(
            model_name='projects',
            name='release_date_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
