# Generated by Django 3.0.4 on 2022-01-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_auto_20200507_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('page_title', models.CharField(max_length=100)),
                ('isNew_indicator', models.BooleanField()),
                ('slider_Content', models.TextField()),
                ('url', models.CharField(max_length=100)),
                ('isAvailable_indicator', models.BooleanField()),
                ('isSlider_available', models.BooleanField()),
                ('isNew_flog', models.BooleanField()),
            ],
        ),
    ]
