# Generated by Django 3.0.4 on 2022-01-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
