# Generated by Django 3.0.4 on 2022-01-06 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_color_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('button_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='button_obj', to='adminapp.Button')),
            ],
        ),
    ]
