# Generated by Django 3.0.4 on 2022-01-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='isNew_indicator',
        ),
    ]
