# Generated by Django 3.0.4 on 2022-01-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_remove_button_isnew_indicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='slider_Content',
        ),
    ]
