# Generated by Django 3.0.4 on 2022-01-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_remove_button_slider_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='button',
            old_name='isNew_flog',
            new_name='isNew_flag',
        ),
    ]
