# Generated by Django 3.0.4 on 2022-02-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_auto_20220110_1142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='color',
        ),
        migrations.DeleteModel(
            name='language',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='button_obj',
        ),
        migrations.DeleteModel(
            name='Button',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
